---

- name: Install EPEL Releases
  yum:
    name: epel-release
    state: present

- name: Install Zabbix Repository
  yum:
    name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
    state: present

- name: Install Zabbix Server and Frontend
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - zabbix-server-mysql
    - zabbix-web-mysql

- name: Copy DB Schema to Server
  copy:
    src: mysql/create_db.sql
    dest: /var/tmp

- name: Create Zabbix DB
  mysql_db:
    name: "{{ zabbix_db_name }}"
    collation: utf8_bin
    encoding: utf8
    target: /var/tmp/create_db.sql
    state: import
  failed_when: false

- name: Create Zabbix DB User
  mysql_user:
    name: "{{ zabbix_db_user }}"
    password: "{{ zabbix_db_pw }}"
    priv: "{{ zabbix_db_name }}.*:ALL"
    state: present

- name: Configure Zabbix Server
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
  notify:
    - restart zabbix server

- name: Start and Enable Zabbix Server
  service:
    name: zabbix-server
    enabled: true
    state: started

- name: Configure PHP date.timezone
  ini_file:
    dest: /etc/php.ini
    section: Date
    option: date.timezone
    value: Australia/Sydney
    backup: yes
  notify:
    - restart httpd server

- name: Start and Enable HTTPD Server
  service:
    name: httpd
    enabled: true
    state: started


