- name: Set connection specific variables
  set_fact:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: 'zabbix'  # If Zabbix WebUI runs on non-default (zabbix) path ,e.g. http://<FQDN>/zabbixeu

# If you want to use Username and Password to be authenticated by Zabbix Server
- name: Set credentials to access Zabbix Server API
  set_fact:
    ansible_user: Admin
    ansible_httpapi_pass: zabbix

- name: update of linux host group 
  community.zabbix.zabbix_maintenance:
    name: Update of linuxserver
    host_name: Zabbix server
    host_groups:
      - LinuxServer
    state: present
    tags:
      - tag: ExampleHostsTag
      - tag: ExampleHostsTag2
        value: ExampleTagValue
      - tag: ExampleHostsTag3
        value: ExampleTagValue
        operator: 0

- name: Create a named maintenance window for hosts zabbix server, with data collection.
  community.zabbix.zabbix_maintenance:
    name: update
    host_names:
      - Zabbix server
    state: present
    collect_data: True

#- name: Remove maintenance window by name
#  community.zabbix.zabbix_maintenance:
#    name: Test1
#    state: absent
